language: node_js

node_js:
  - '8'

install:
  - yarn
  - yarn lerna bootstrap

script:
  - yarn build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo --dry-run"
